version: '3.8'

services:
  api-gateway:
    image: api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - back
      - front

  back:
    image: back:latest

  front:
    image: front:latest